### ISSUE TITLE
disbale about this video translate

### ISSUE THREAD

**Issue by seong1995** [zpix1/yt-anti-translate#1]
![image](https://user-images.githubusercontent.com/69965367/111921080-9228ac80-8acd-11eb-8d8a-288377c50abf.png)

as image show, after enable extension, about this video layout is still translate to endglish.

**Comment by zpix1** [comment]
Hi,
I've added description anti-translation in the YT AT 1.4 version.
You can update and test that feature as soon as google approves update and add it to chrome store.
Thanks for your interest in my extension.
