### ISSUE TITLE
Compatibility with another extension: DeArrow

### ISSUE THREAD

**Issue by R4ygen** [zpix1/yt-anti-translate#21]
While using this extension along with the [DeArrow](https://github.com/ajayyy/DeArrow/) extension, the original title is repeated after the modified title from DeArrow:
![image](https://github.com/zpix1/yt-anti-translate/assets/49517480/16193b81-6464-4736-902f-257e2d002746)

Reloading the page fixes the issue temporarily for that video.

N.B.: I'm using the [Firefox port](https://addons.mozilla.org/en-US/firefox/addon/youtube-anti-translate/) of the extension! that's still stuck at the 1.5.7 version

**Comment by ajayyy** [comment]
https://github.com/zpix1/yt-anti-translate/pull/20

the port is out of date as I did make a fix for that

**Comment by R4ygen** [comment]
Nice to know! I'll leave a comment on the extension page to prompt the dev to update
