### ISSUE TITLE
Video titles suddenly multiplied when scrolling

### ISSUE THREAD

**Issue by xnovaq** [zpix1/yt-anti-translate#26]
Scrolling down and back up multiplies video title endlessly in the title bar. It becomes something like "[video title][video title][video title][video title][video title][video title][video title] - YouTube"

**Comment by MoeHunt3r** [comment]
Don't know if we mean the same but I have an simmilar issue
![Screenshot](https://github.com/zpix1/yt-anti-translate/assets/38086254/6b8f65ae-d4af-45af-84e1-4b864f269bc5)

**Comment by zpix1** [comment]
I hope this issue will be fixed in 1.5.14, please check it

**Comment by WinstonWantsAUserName** [comment]
> I hope this issue will be fixed in 1.5.14, please check it

Can you please update it in chrome web store? Thank you.

**Comment by zpix1** [comment]
Now should be available in Chrome Store

**Comment by zpix1** [comment]
It should be fixed now, 1.5.14
