### ISSUE TITLE
The estension seems to work nice. Are there plans to implement it on Firefox?

### ISSUE THREAD

**Issue by EfraMP** [zpix1/yt-anti-translate#3]

**Comment by zpix1** [comment]
Don't have time for it now, maybe someone can convert it and publish under their firefox store account (or what firefox uses for extensions)

**Comment by zpix1** [comment]
Looks like someone did it: https://addons.mozilla.org/ru/firefox/addon/youtube-anti-translate/, so thanks, Jan.
Please note I have nothing to do with it, so I can't fix any bugs.
Maybe we should make a github action to deliver same (maybe with some browser specific changes) code to chrome\firefox stores synchronously. I tried to set up CD for chrome webstore, but it fails with 400 error for some reason.
