### ISSUE TITLE
Gettting Uncaught TypeError: ytInitialPlayerResponse is undefined debugger eval code:58:13 when running background.js

### ISSUE THREAD

**Issue by artisticfox8** [zpix1/yt-anti-translate#4]
Looking at background.js, where is ytInitialPlayerResponse even defined? There is no let ytInitialPlayerResponse; So, it does not work. The first time you mention it is on line 58. Are there any dependencies? 
Regards, artisticfox8

**Comment by artisticfox8** [comment]
It happens on the Chrome extension as well as in Firefox Devtools console.
![youtube antitranslate error](https://user-images.githubusercontent.com/77014769/135760875-8ed969fb-68c4-46ac-8df5-7acbd28d5245.png)

**Comment by zpix1** [comment]
It's `window.ytInitialPlayerResponse` object Youtube creates whenever you open video page. Should've added some checks and `window.` prefix for clarity, but it works without them. It will be cool if you create a pull request with something like `if (!window.ytInitialPlayerResponse) { return; }` to avoid type errors.

**Comment by artisticfox8** [comment]
> It's `window.ytInitialPlayerResponse` object Youtube creates whenever you open video page. Should've added some checks and `window.` prefix for clarity, but it works without them. It will be cool if you create a pull request with something like `if (!window.ytInitialPlayerResponse) { return; }` to avoid type errors.

Your extension does not work on the screenshot I posted BTW. The title remains Russian.
